'use strict';
const path = require('node:path');
const {lexical} = require('./filesystem');
const INDEX_MARKER='<!-- Generated by harness documentation; do not edit by hand. -->';
function escape(value) {
  return String(value).replace(/&/g,'&amp;').replace(/[|<>\[\]`*_\r\n]/g,c=>`&#${c.charCodeAt(0)};`);
}
function href(name) {return name.split('/').map(part=>encodeURIComponent(part).replace(/[!'()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase())).join('/');}
function replaceMarkers(text,blocks) {
  const stack=[],managed=new Set(['tree','modules','docs']);
  for(const token of text.matchAll(/<!--\s*\/?\s*AUTO\s*:[^\r\n]*/g)) {
    const match=/^<!-- (\/?)AUTO:([A-Za-z0-9_-]+) -->$/.exec(token[0]);
    if(!match)throw new Error('Malformed AUTO marker');
    const [,closing,name]=match;
    if(closing) {if(stack.pop()!==name)throw new Error('Unbalanced AUTO markers');}
    else {if(stack.length && (managed.has(name)||stack.some(item=>managed.has(item))))throw new Error('Nested AUTO markers crossing a managed region');stack.push(name);}
  }
  if(stack.length)throw new Error('Unbalanced AUTO markers');
  const regions=[];
  for(const name of ['tree','modules','docs']) {
    const open=`<!-- AUTO:${name} -->`,close=`<!-- /AUTO:${name} -->`;
    const near=text.match(new RegExp(`<!--\\s*/?AUTO:${name}\\b[^\\n]*`,'g'))||[];
    const starts=[...text.matchAll(new RegExp(open,'g'))].map(m=>m.index);
    const ends=[...text.matchAll(new RegExp(close,'g'))].map(m=>m.index);
    if(!starts.length && !ends.length && !near.length && name!=='docs')continue;
    if(starts.length!==1 || ends.length!==1 || near.length!==2 || starts[0]>=ends[0])throw new Error(`Malformed or duplicate AUTO:${name} markers`);
    const a=starts[0],b=ends[0];
    for(const [offset,token] of [[a,open],[b,close]]) {
      if(offset>0 && text[offset-1]!=='\n')throw new Error(`Marker must occupy its own line: AUTO:${name}`);
      const after=text.slice(offset+token.length);
      if(after && !/^(?:\r?\n)/.test(after))throw new Error(`Marker must occupy its own line: AUTO:${name}`);
    }
    regions.push({name,start:a+open.length,end:b,outerStart:a,outerEnd:b+close.length});
  }
  regions.sort((a,b)=>a.start-b.start);
  for(let i=1;i<regions.length;i++)if(regions[i].outerStart<regions[i-1].outerEnd)throw new Error('Nested AUTO markers');
  const newline=text.includes('\r\n')?'\r\n':'\n';
  for(const region of regions.reverse()) text=text.slice(0,region.start)+newline+blocks[region.name].replace(/\n/g,newline)+newline+text.slice(region.end);
  return text;
}
function renderIndex(documents,docsRoot,index,sources=[]) {
  let content=INDEX_MARKER+'\n# Documentation index\n\n';
  content+='Use maintained guidance, status, and reference documents for current decisions. Proposals, snapshots, and history may not represent current authority.\n';
  const groups=new Map();
  for(const doc of documents) {const group=doc.metadata?doc.metadata.type:'missing';if(!groups.has(group))groups.set(group,[]);groups.get(group).push(doc);}
  const order=[['guidance','Guidance'],['status','Status'],['reference','Reference'],['proposal','Proposals'],['generated','Generated'],['history','History'],['temporary','Temporary'],['missing','Needs classification']];
  for(const [group,title] of order) {
    if(!groups.has(group))continue;
    content+=`\n## ${title}\n\n| Document | Status | Description | Read when |\n| --- | --- | --- | --- |\n`;
    for(const doc of groups.get(group).sort((a,b)=>lexical(a.path,b.path))) {
      const relative=path.posix.relative(path.posix.dirname(index),doc.path);
      const record=doc.metadata||{title:doc.path.slice(docsRoot.length+1),status:'Unclassified',description:'',read_when:''};
      content+=`| [${escape(record.title)}](${href(relative)}) | ${escape(record.status)} | ${escape(record.description)} | ${escape(record.read_when)} |\n`;
    }
  }
  if(!documents.length)content+='\nNo documentation files found.\n';
  content+='\n## Source inventory\n\nFilenames only; module purposes belong in authored documentation.\n\n';
  content+=sources.length?sources.map(name=>`- [${escape(name)}](${href(path.posix.relative(path.posix.dirname(index),name))})`).join('\n')+'\n':'No source files found.\n';
  return content;
}
function renderInstruction(text,sources,config) {
  const link=`[Source inventory](${href(config.index)}#source-inventory)`;
  const counts=config.sourceRoots.map(root=>[root,sources.filter(name=>name.startsWith(root+'/')||name===root).length]);
  const inventory=link+'\n'+counts.map(([root,count])=>`- ${escape(root)}: ${count} files`).join('\n');
  const modules=link+'\n\n| Source root | Files |\n| --- | --- |\n'+counts.map(([root,count])=>`| ${escape(root)} | ${count} |`).join('\n');
  return replaceMarkers(text,{tree:inventory,modules,docs:`[Documentation index](${href(config.index)})`});
}
module.exports={INDEX_MARKER,escape,href,replaceMarkers,renderIndex,renderInstruction};
