'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {execFileSync} = require('node:child_process');
const {generate, build, buildFromReader, loadConfig} = require('../../plugins/documentation/skills/documentation/scripts/generate');
const {working} = require('../../plugins/documentation/skills/documentation/scripts/filesystem');
const marker = '<!-- Generated by harness documentation; do not edit by hand. -->';
const config = {version:1, sourceRoots:['src'], docsRoot:'docs', instruction:'CLAUDE.md', index:'docs/index.md', strict:false};
const meta = {title:'Guide', description:'A useful guide', type:'guidance', status:'maintained', read_when:'Making a change'};
const header = (record=meta) => '---\n' + Object.entries(record).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n') + '\n---\nBody\n';
function put(root, name, content) { const file=path.join(root,name); fs.mkdirSync(path.dirname(file),{recursive:true}); fs.writeFileSync(file,content); }
function fixture(t) {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'documentation engine \u00fc '));
  t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  put(root,'documentation.config.json',JSON.stringify(config));
  put(root,'CLAUDE.md','Authored\r\n<!-- AUTO:docs -->\r\nold\r\n<!-- /AUTO:docs -->\r\nTail\r\n');
  put(root,'docs/guide.md',header()); put(root,'src/a.js','do not read source payload');
  return root;
}
function git(root,...args) { return execFileSync('git',['-c','core.autocrlf=false',...args],{cwd:root,encoding:'utf8'}); }
function init(root) { git(root,'init','--quiet'); git(root,'add','.'); }
test('exports canonical generator',()=>assert.equal(typeof generate,'function'));
test('refresh builds deterministic owned output and preserves authored CRLF bytes',t=>{
  const root=fixture(t); put(root,'src/z].js','x'); put(root,'docs/z].pdf',Buffer.from([0,255]));
  put(root,'docs/catalog.json',JSON.stringify({'z].pdf':{...meta,title:'Attachment | [x]'}}));
  const first=generate(root); const again=generate(root);
  assert.deepEqual(first,again); assert.deepEqual(first.missing,[]);
  assert.ok(first.outputs['docs/index.md'].startsWith(marker+'\n'));
  assert.ok(first.outputs['docs/index.md'].includes('Attachment &#124; &#91;x&#93;'));
  assert.ok(first.outputs['docs/index.md'].includes('z%5D.pdf'));
  assert.equal(fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8'),first.outputs['CLAUDE.md']);
  assert.ok(first.outputs['CLAUDE.md'].startsWith('Authored\r\n'));
  assert.ok(first.outputs['CLAUDE.md'].endsWith('\r\nTail\r\n'));
  assert.doesNotThrow(()=>generate(root,{check:true}));
});
test('source markers use only escaped filename inventory',t=>{
  const root=fixture(t); put(root,'CLAUDE.md','Before\n<!-- AUTO:tree -->\nold\n<!-- /AUTO:tree -->\n<!-- AUTO:modules -->\nold\n<!-- /AUTO:modules -->\n<!-- AUTO:docs -->\nold\n<!-- /AUTO:docs -->\nAfter');
  const outputs=build(root).outputs; assert.ok(outputs['docs/index.md'].includes('src/a.js'));
  assert.ok(!outputs['CLAUDE.md'].includes('do not read source payload'));
  assert.ok(outputs['CLAUDE.md'].endsWith('\nAfter'));
});
test('missing metadata is visible by default; strict rejects before mutation',t=>{
  const root=fixture(t); put(root,'docs/missing.md','No metadata');
  const result=build(root); assert.deepEqual(result.missing,['docs/missing.md']);
  assert.ok(result.outputs['docs/index.md'].includes('Needs classification'));
  assert.throws(()=>generate(root,{strict:true}),/Missing metadata/);
  assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
});
test('read-only build overlays and check validate every output',t=>{
  const root=fixture(t); const reader=working(root,{'docs/new.md':header({...meta,title:'New'})});
  const result=buildFromReader(reader,loadConfig(reader)); assert.ok(result.outputs['docs/index.md'].includes('New'));
  assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
  generate(root); put(root,'docs/index.md',marker+'\nStale\n');
  assert.throws(()=>generate(root,{check:true}),/Stale.*docs\/index.md/);
  assert.equal(fs.readFileSync(path.join(root,'docs/index.md'),'utf8'),marker+'\nStale\n');
});
test('add delete rename updates docs without self indexing',t=>{
  const root=fixture(t); generate(root); fs.renameSync(path.join(root,'docs/guide.md'),path.join(root,'docs/renamed.md'));
  put(root,'docs/new.md',header({...meta,title:'New'})); const output=generate(root).outputs['docs/index.md'];
  assert.ok(output.includes('renamed.md')); assert.ok(!output.includes('(guide.md)'));
  assert.ok(!output.includes('(index.md)')); assert.ok(!output.includes('(catalog.json)'));
  fs.unlinkSync(path.join(root,'docs/new.md')); assert.ok(!generate(root).outputs['docs/index.md'].includes('(new.md)'));
});
test('flat grammar rejects malformed, unknown and conflicting metadata before writes',t=>{
  const root=fixture(t);
  const cases=[header({...meta,extra:'no'}),header({...meta,type:'wrong'}),header({...meta,status:'wrong'}),'---\ntitle: [nested]\n---\n','---\ntitle: A\ntitle: B\n---\n','---\ntitle: A\n'];
  for(const content of cases) {put(root,'docs/guide.md',content); assert.throws(()=>generate(root),/metadata|frontmatter|field|type|status/i);}
  put(root,'docs/guide.md',header()); put(root,'docs/catalog.json',JSON.stringify({'guide.md':{...meta,title:'Conflict'}}));
  assert.throws(()=>generate(root),/Conflicting/); assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
});
test('catalog accepts identical full metadata and exact legacy records',t=>{
  const root=fixture(t); put(root,'docs/catalog.json',JSON.stringify({'guide.md':meta,'legacy.pdf':{title:'Legacy',type:'reference',status:'snapshot',note:'Legacy note'}}));
  put(root,'docs/legacy.pdf','attachment'); assert.deepEqual(build(root).missing,[]);
  put(root,'docs/catalog.json','{"guide.md":{},"guide.md":{}}'); assert.throws(()=>build(root),/Duplicate/);
  put(root,'docs/catalog.json',JSON.stringify({'guide.md':{...meta,note:'mixed'}})); assert.throws(()=>build(root),/Unknown|field/);
});
test('headers and control files are bounded; attachments and source contents never read',t=>{
  const root=fixture(t); put(root,'docs/guide.md',header()+'x'.repeat(300000));
  put(root,'docs/blob.pdf',Buffer.alloc(300000)); put(root,'src/huge.js',Buffer.alloc(300000));
  const original=fs.openSync; const opened=[];
  fs.openSync=function(file,...args){opened.push(String(file)); return original.call(this,file,...args);};
  try { build(root); } finally {fs.openSync=original;}
  assert.ok(!opened.some(p=>p.endsWith('blob.pdf')||p.endsWith('huge.js')));
  put(root,'docs/guide.md','---\n'+'x'.repeat(20000)); assert.throws(()=>build(root),/frontmatter|bounded/);
});
test('config rejects escapes, sensitive roots, root overlap and unknown keys',t=>{
  const root=fixture(t);
  for(const change of [{sourceRoots:['.']},{sourceRoots:['../other']},{sourceRoots:['private']},{sourceRoots:['.hidden']},{sourceRoots:['docs/sub']},{sourceRoots:['src','src/sub']},{docsRoot:'src/docs'},{index:'other/index.md'},{instruction:'README.md'},{extra:1},{strict:'false'}]) {
    put(root,'documentation.config.json',JSON.stringify({...config,...change})); assert.throws(()=>build(root),/config|path|root|instruction|index|strict|Unknown/i);
  }
});
test('hidden and blocked children are excluded from inventory',t=>{
  const root=fixture(t); for(const name of ['private','secrets','runs','outputs','fixtures','node_modules','build','.cache']) {put(root,`docs/${name}/hidden.md`,'x'); put(root,`src/${name}/secret.js`,'x');}
  assert.deepEqual(build(root).missing,[]);
});
test('malformed markers fail and generated indexes require ownership',t=>{
  const root=fixture(t); for(const content of ['Authored','<!-- AUTO:docs -->','<!-- /AUTO:docs -->\n<!-- AUTO:docs -->','<!-- AUTO:docs -->\n<!-- AUTO:docs -->\n<!-- /AUTO:docs -->','<!-- AUTO:docs -->\n<!-- /AUTO:docs -->\n<!-- AUTO:tree -->']) {
    put(root,'CLAUDE.md',content); assert.throws(()=>generate(root),/marker/i);
  }
  put(root,'CLAUDE.md','<!-- AUTO:docs -->\n<!-- /AUTO:docs -->'); put(root,'docs/index.md','# Authored');
  assert.throws(()=>generate(root),/owned|Generated|ownership/i);
});
test('linked roots and linked output parents are rejected',t=>{
  const root=fixture(t); const outside=fs.mkdtempSync(path.join(os.tmpdir(),'doc-link-'));
  t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));
  fs.symlinkSync(outside,path.join(root,'linked'),'junction');
  put(root,'documentation.config.json',JSON.stringify({...config,sourceRoots:['linked']})); assert.throws(()=>build(root),/link/i);
  put(root,'documentation.config.json',JSON.stringify({...config,index:'docs/linked/index.md'})); fs.symlinkSync(outside,path.join(root,'docs/linked'),'junction'); assert.throws(()=>build(root),/link/i);
});
test('staged checks exact index despite working config docs and instruction divergence',t=>{
  const root=fixture(t); generate(root); init(root);
  put(root,'docs/guide.md','---\nbad: working-only\n---'); put(root,'documentation.config.json','invalid working'); put(root,'CLAUDE.md','malformed working');
  assert.doesNotThrow(()=>generate(root,{staged:true}));
  assert.equal(fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8'),'malformed working');
  assert.throws(()=>generate(root,{check:true}),/config|JSON/i);
});
test('staged add delete rename use only staged filenames and staged outputs',t=>{
  const root=fixture(t); generate(root); init(root);
  git(root,'mv','docs/guide.md','docs/renamed.md'); assert.throws(()=>generate(root,{staged:true}),/Stale/);
  generate(root); git(root,'add','docs/index.md','CLAUDE.md'); assert.doesNotThrow(()=>generate(root,{staged:true}));
  git(root,'rm','-f','docs/renamed.md'); assert.throws(()=>generate(root,{staged:true}),/Stale/);
  generate(root); git(root,'add','docs/index.md','CLAUDE.md'); assert.doesNotThrow(()=>generate(root,{staged:true}));
  put(root,'docs/new.md',header()); git(root,'add','docs/new.md'); assert.throws(()=>generate(root,{staged:true}),/Stale/);
});
test('staged rejects symlink modes and unresolved entries in scope',t=>{
  const root=fixture(t); generate(root); init(root);
  const sha=git(root,'hash-object','-w','--stdin');
  git(root,'update-index','--add','--cacheinfo',`120000,${sha.trim()},docs/link.md`);
  assert.throws(()=>generate(root,{staged:true}),/mode|regular|link/i);
  git(root,'update-index','--force-remove','docs/link.md');
  execFileSync('git',['update-index','--index-info'],{cwd:root,input:`100644 ${sha.trim()} 1\tdocs/conflict.md\n`});
  assert.throws(()=>generate(root,{staged:true}),/unresolved|stage/i);
});


test('index prioritizes current guidance and leaves missing classification last',t=>{
  const root=fixture(t);
  for(const type of ['status','reference','proposal','generated','history','temporary'])put(root,`docs/${type}.md`,header({...meta,type}));
  put(root,'docs/unclassified.md','Unclassified'); const result=build(root);
  const index=result.outputs['docs/index.md'];
  const headings=['Guidance','Status','Reference','Proposals','Generated','History','Temporary','Needs classification','Source inventory'];
  let offset=-1; for(const heading of headings) {const next=index.indexOf(`## ${heading}\n`);assert.ok(next>offset,heading);offset=next;}
  assert.match(index,/history.*authority|history.*authoritative/i);
});
test('instruction inventories stay compact while index lists all source filenames',t=>{
  const root=fixture(t); put(root,'CLAUDE.md','<!-- AUTO:tree -->\nold\n<!-- /AUTO:tree -->\n<!-- AUTO:modules -->\nold\n<!-- /AUTO:modules -->\n<!-- AUTO:docs -->\nold\n<!-- /AUTO:docs -->');
  for(let i=0;i<100;i++)put(root,`src/file-${i}.js`,'Unread');
  const result=build(root); assert.ok(result.outputs['CLAUDE.md'].length<1000);
  assert.match(result.outputs['CLAUDE.md'],/101/);assert.ok(!result.outputs['CLAUDE.md'].includes('file-99.js'));
  assert.ok(result.outputs['docs/index.md'].includes('src/file-99.js'));
});
test('frontmatter rejects legacy catalog fields and Windows path aliases',t=>{
  const root=fixture(t);put(root,'docs/guide.md',header({title:'Legacy',type:'reference',status:'snapshot',note:'Note'}));
  assert.throws(()=>build(root),/Unknown.*note/);put(root,'docs/guide.md',header());
  for(const source of ['private.','private ','secrets.','.. ','con','src/NUL.txt','src/a?b']) {
    put(root,'documentation.config.json',JSON.stringify({...config,sourceRoots:[source]}));assert.throws(()=>build(root),/path/i);
  }
  for(const index of ['docs/catalog.json','docs/index.txt']) {put(root,'documentation.config.json',JSON.stringify({...config,index}));assert.throws(()=>build(root),/index/i);}
});
test('staged bounded headers support large bodies and partial staging',t=>{
  const root=fixture(t);put(root,'docs/guide.md',header()+'x'.repeat(300000));generate(root);init(root);
  assert.doesNotThrow(()=>generate(root,{staged:true}));
  put(root,'docs/guide.md',header({...meta,title:'Working only'}));
  put(root,'src/a.js','Different unread contents');
  fs.unlinkSync(path.join(root,'docs/index.md'));assert.doesNotThrow(()=>generate(root,{staged:true}));
  git(root,'add','docs/guide.md');assert.throws(()=>generate(root,{staged:true}),/Stale/);
});
test('readers never request attachment or source payloads even in staged builds',t=>{
  const root=fixture(t);put(root,'docs/attachment.pdf','Unread'); const reader=working(root),requested=[];
  const original=reader.read; reader.read=function(name,...args){requested.push(name);return original(name,...args);};
  buildFromReader(reader);assert.ok(!requested.includes('docs/attachment.pdf'));assert.ok(!requested.includes('src/a.js'));
});
test('staged rejects a linked configured ancestor while unrelated modes are ignored',t=>{
  const root=fixture(t);generate(root);init(root);const sha=git(root,'hash-object','-w','--stdin');
  git(root,'update-index','--add','--cacheinfo',`120000,${sha.trim()},unrelated/link`);
  assert.doesNotThrow(()=>generate(root,{staged:true}));
  git(root,'update-index','--add','--cacheinfo',`120000,${sha.trim()},external`);
  put(root,'documentation.config.json',JSON.stringify({...config,sourceRoots:['external/src']}));git(root,'add','documentation.config.json');
  assert.throws(()=>generate(root,{staged:true}),/mode|regular|link/i);
});
test('invalid UTF-8 instructions fail before bytes outside markers can change',t=>{
  const root=fixture(t);const content=Buffer.concat([Buffer.from([255]),Buffer.from('\n<!-- AUTO:docs -->\n<!-- /AUTO:docs -->')]);
  put(root,'CLAUDE.md',content);assert.throws(()=>generate(root),/UTF-8/);
  assert.deepEqual(fs.readFileSync(path.join(root,'CLAUDE.md')),content);assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
});
test('self-index exclusion handles Windows casing and config strict default',t=>{
  const root=fixture(t);generate(root);
  put(root,'documentation.config.json',JSON.stringify({...config,index:'docs/INDEX.md'}));
  if(process.platform==='win32')assert.deepEqual(build(root).missing,[]);
  put(root,'documentation.config.json',JSON.stringify({...config,strict:true}));put(root,'docs/missing.pdf','Unknown');
  assert.throws(()=>generate(root),/Missing metadata/);
});
test('configured roots cannot alias control files or instruction output',t=>{
  const root=fixture(t);
  for(const change of [{docsRoot:'CLAUDE.md',index:'CLAUDE.md/index.md'},{docsRoot:'documentation.config.json',index:'documentation.config.json/index.md'},{sourceRoots:['CLAUDE.md/sub']},{sourceRoots:['documentation.config.json']}]) {
    put(root,'documentation.config.json',JSON.stringify({...config,...change}));
    assert.throws(()=>require('../../plugins/documentation/skills/documentation/scripts/generate').validateConfig({...config,...change}),/root|control/i);
  }
});
test('oversized rendered outputs fail preflight with actionable diagnostics',t=>{
  const root=fixture(t); const reader=working(root);
  reader.files=scope=>scope==='src'?Array.from({length:14000},(_,i)=>`src/module-${String(i).padStart(5,'0')}-long-component.js`):[];
  assert.throws(()=>buildFromReader(reader),/Generated output.*docs\/index.md.*1 MiB|Generated output.*1 MiB.*docs\/index.md/);
  assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
  const authored='a'.repeat(1048576-60)+'\n<!-- AUTO:docs -->\n<!-- /AUTO:docs -->\n';
  put(root,'CLAUDE.md',authored);assert.throws(()=>generate(root),/Generated output.*CLAUDE.md.*1 MiB|Generated output.*1 MiB.*CLAUDE.md/);
  assert.equal(fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8'),authored);
  assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
});
test('managed markers reject unknown nested markers while preserving outside regions',t=>{
  const root=fixture(t);
  for(const nested of ['<!-- AUTO:unexpected -->','<!-- AUTO:unexpected -->\nNested\n<!-- /AUTO:unexpected -->','<!-- AUTO:unexpected','<!-- /AUTO:unexpected -->']) {
    put(root,'CLAUDE.md',`Authored\n<!-- AUTO:docs -->\n${nested}\n<!-- /AUTO:docs -->\nTail`);
    assert.throws(()=>generate(root),/nested|marker/i);assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
  }
  const outside='<!-- AUTO:custom -->\r\nAuthored custom text\r\n<!-- /AUTO:custom -->\r\n';
  put(root,'CLAUDE.md',outside+'<!-- AUTO:docs -->\r\nold\r\n<!-- /AUTO:docs -->\r\nTail');
  const result=generate(root);assert.ok(result.outputs['CLAUDE.md'].startsWith(outside));
});
test('JSON control whitespace is rejected in configuration and catalog',t=>{
  const root=fixture(t);put(root,'documentation.config.json','\u000b'+JSON.stringify(config));
  assert.throws(()=>build(root),/config.*JSON|JSON/i);
  put(root,'documentation.config.json',JSON.stringify(config));put(root,'docs/catalog.json','\u000b'+JSON.stringify({'guide.md':meta}));
  assert.throws(()=>build(root),/catalog.*JSON|JSON/i);
});
test('unknown marker nesting cannot cross a managed region',t=>{
  const root=fixture(t);const cases=[
    '<!-- AUTO:custom -->\n<!-- AUTO:docs -->\nold\n<!-- /AUTO:docs -->\n<!-- /AUTO:custom -->',
    '<!-- AUTO:custom -->\n<!-- AUTO:docs -->\n<!-- /AUTO:custom -->\n<!-- /AUTO:docs -->'
  ];
  for(const text of cases){put(root,'CLAUDE.md',text);assert.throws(()=>generate(root),/nested|marker/i);}
});
test('exports CLI entrypoint for the full-harness compatibility launcher',()=>{
  assert.equal(typeof require('../../plugins/documentation/skills/documentation/scripts/generate').cli,'function');
});
test('managedMarkers docs-only preserves existing tree and module bytes',t=>{
  const root=fixture(t);put(root,'documentation.config.json',JSON.stringify({...config,managedMarkers:['docs']}));
  const tree='<!-- AUTO:tree -->\r\nAuthored Python inventory \u00fc\r\n<!-- /AUTO:tree -->';
  const modules='<!-- AUTO:modules -->\r\n| Module | Authored purpose |\r\n<!-- /AUTO:modules -->';
  put(root,'CLAUDE.md',`Before\r\n${tree}\r\n${modules}\r\n<!-- AUTO:docs -->\r\nold\r\n<!-- /AUTO:docs -->\r\nAfter`);
  const output=generate(root).outputs['CLAUDE.md'];assert.ok(output.includes(tree));assert.ok(output.includes(modules));
  assert.ok(output.includes('[Documentation index](docs/index.md)'));assert.doesNotThrow(()=>generate(root,{check:true}));
  init(root);assert.doesNotThrow(()=>generate(root,{staged:true}));
  put(root,'CLAUDE.md','Working-only malformed instruction');assert.doesNotThrow(()=>generate(root,{staged:true}));
});
test('managedMarkers supports explicit tree ownership while retaining module block',t=>{
  const root=fixture(t);put(root,'documentation.config.json',JSON.stringify({...config,managedMarkers:['docs','tree']}));
  put(root,'CLAUDE.md','<!-- AUTO:tree -->\nOld tree\n<!-- /AUTO:tree -->\n<!-- AUTO:modules -->\nAuthored modules\n<!-- /AUTO:modules -->\n<!-- AUTO:docs -->\nold\n<!-- /AUTO:docs -->');
  const output=build(root).outputs['CLAUDE.md'];assert.ok(!output.includes('Old tree'));assert.ok(output.includes('Authored modules'));assert.ok(output.includes('Source inventory'));
});
test('managedMarkers rejects invalid lists and validates unowned known markers',t=>{
  const root=fixture(t);
  for(const managedMarkers of [null,[],['tree'],['docs','docs'],['docs','unknown'],'docs',[1,'docs']]) {
    put(root,'documentation.config.json',JSON.stringify({...config,managedMarkers}));assert.throws(()=>build(root),/Invalid managedMarkers/i);
  }
  put(root,'documentation.config.json',JSON.stringify({...config,managedMarkers:['docs']}));
  put(root,'CLAUDE.md','<!-- AUTO:tree -->\nUnbalanced authored tree\n<!-- AUTO:docs -->\nold\n<!-- /AUTO:docs -->');
  assert.throws(()=>generate(root),/marker/i);assert.ok(!fs.existsSync(path.join(root,'docs/index.md')));
});
test('Python cache presence does not change working or staged documentation',t=>{
  const root=fixture(t);const baseline=generate(root);init(root);
  put(root,'src/__pycache__/module.cpython-313.pyc',Buffer.from([0,255,42]));
  put(root,'docs/__pycache__/cached.pyc',Buffer.from([0,255,43]));
  const refreshed=generate(root);assert.deepEqual(refreshed,baseline);
  assert.doesNotThrow(()=>generate(root,{staged:true}));
  git(root,'add','src/__pycache__/module.cpython-313.pyc','docs/__pycache__/cached.pyc');
  assert.doesNotThrow(()=>generate(root,{staged:true}));
  assert.deepEqual(build(root).outputs,baseline.outputs);
});
test('Windows autocrlf checkout preserves generated index newline checks',t=>{
  const root=fixture(t);generate(root);init(root);
  git(root,'-c','core.autocrlf=true','add','--renormalize','.');
  git(root,'-c','user.name=Synthetic Test','-c','user.email=synthetic@example.invalid','commit','--quiet','-m','Synthetic fixture');
  fs.unlinkSync(path.join(root,'docs/index.md'));
  git(root,'-c','core.autocrlf=true','checkout','--','docs/index.md');
  const checkedOut=fs.readFileSync(path.join(root,'docs/index.md'),'utf8');assert.ok(checkedOut.includes('\r\n'));
  assert.doesNotThrow(()=>generate(root,{check:true}));assert.doesNotThrow(()=>generate(root,{staged:true}));
  assert.equal(build(root).outputs['docs/index.md'],checkedOut);
});
