/** Repo wrapper uses the canonical engine without changing the real checkout. */
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const {execFileSync} = require('node:child_process');
const SCRIPT = path.resolve(__dirname, '../../scripts/repo-generate-docs.js');
let root;
beforeEach(() => {
  root = fs.mkdtempSync(path.join(os.tmpdir(), 'repo-documentation-'));
  for (const directory of ['skills/readiness','scripts','tests/evals/fixtures']) {
    fs.mkdirSync(path.join(root, directory), {recursive: true});
  }
  fs.writeFileSync(path.join(root, 'skills/readiness/SKILL.md'), '# Readiness');
  fs.writeFileSync(path.join(root, 'scripts/example.js'), 'must never read source');
  fs.writeFileSync(path.join(root, 'tests/evals/fixtures/excluded.js'), 'excluded');
  fs.writeFileSync(path.join(root, 'documentation.config.json'), JSON.stringify({
    version: 1, sourceRoots: ['skills','scripts','tests'], docsRoot:'docs',
    instruction:'CLAUDE.md', index:'docs/index.md', strict:false,
  }));
  fs.writeFileSync(path.join(root, 'CLAUDE.md'), [
    'Authored guidance', '<!-- AUTO:tree -->', 'old tree', '<!-- /AUTO:tree -->',
    '<!-- AUTO:modules -->', 'old modules', '<!-- /AUTO:modules -->',
    '<!-- AUTO:docs -->', 'old map', '<!-- /AUTO:docs -->',
  ].join('\n'));
});
afterEach(() => fs.rmSync(root, {recursive:true, force:true}));
function run(args=[]) {
  return execFileSync(process.execPath, [SCRIPT, '--root', root, ...args], {cwd:root, encoding:'utf8'});
}
test('refreshes compact markers and puts source filenames in the index', () => {
  run();
  const instructions = fs.readFileSync(path.join(root,'CLAUDE.md'),'utf8');
  const index = fs.readFileSync(path.join(root,'docs/index.md'),'utf8');
  expect(instructions).toContain('Authored guidance');
  expect(instructions).toContain('Source inventory');
  expect(instructions).not.toContain('old tree');
  expect(instructions).not.toContain('old modules');
  expect(index).toContain('skills/readiness/SKILL.md');
  expect(index).toContain('scripts/example.js');
  expect(index).not.toContain('excluded.js');
});
test('check validates both outputs without writes', () => {
  run();
  run(['--check']);
  const before = fs.readFileSync(path.join(root,'CLAUDE.md'));
  fs.writeFileSync(path.join(root,'docs/index.md'), '<!-- Generated by harness documentation; do not edit by hand. -->\nstale\n');
  expect(() => run(['--check'])).toThrow();
  expect(fs.readFileSync(path.join(root,'CLAUDE.md'))).toEqual(before);
});
test('does not stage refreshed output', () => {
  execFileSync('git', ['init','--quiet'], {cwd:root});
  run();
  const staged = execFileSync('git', ['diff','--cached','--name-only'], {cwd:root,encoding:'utf8'});
  expect(staged).toBe('');
});
